// Copyright Steven Bosnick 2016. All rights reserved.
// Use of this source code is governed by the GNU General Public License version 3.
// See the file COPYING for your rights under that license.

//go:generate go run mkcurrency.go

package domain

type Currency uint

type currencyInfo struct {
	symbol     string
	name       string
	number     int
	minorUnits int
}

func (c Currency) String() string {
	if int(c*3+3) > len(currencyStringsBlock) {
		c = 0
	}

	// This slice calculation relies on the manner in which
	// currencyStringBlock is generated by mkcurrency.go. The string block
	// is generated in the same order as the Currency constants and each
	// element of the block is 3 uppercase characters from [A-Z].
	return currencyStringsBlock[c*3 : c*3+3]
}
